### ISSUE TITLE
Проблема с созданием тестов

### ISSUE THREAD

**Issue by tosolya** [tosolya/Gradle1#1]
@coursar

**Шаги воспроизведения:**
1. Пишу код согласно вашему видио по Lombok, дохожу до момента создания Тестов
2. Из класс CarService пытаюсь создать Тесты
3. Нажимаю command+shift+T наведя на имя класса и вылезает ошибка 

**Ожид.результат:**
Появится менюшка для создания теста с выбором методов
**Факт.результат:**
Появляется ошибка "No test subjects found"

![Desktop 2021-03-20 15-26-00 2021-03-20 15-26-17](https://user-images.githubusercontent.com/75759854/111869490-e417e800-8990-11eb-86b7-541861a3bb7c.png)

macOS Catalina 10.15.7
Java 11

https://github.com/tosolya/Gradle1

**Comment by tosolya** [comment]
ok

**Comment by coursar** [comment]
Когда во вкладке иконка серая с буквой j внизу на красном фоне (как у вас), значит, что IDEA не понимает, что этот файл находится в модели вашего проекта. Из-за этого функции работать не будут.
